### ISSUE TITLE
Method key does not exist on T.class_of(Types::UserType)

### ISSUE THREAD

**Issue by kxuenvoy** [Gusto/apollo-federation-ruby#183]
Hi, I am trying to use apollo-fderation-ruby in my project. 

After I added key keyword. 'bundle exec srb tc' check will fail as below. Any Idea how to resolve this problem.

Quote:
app/graphql/types/user_type.rb:10: Method key does not exist on T.class_of(Types::UserType) https://srb.help/7003
    10 |    key fields: :id
END.

**Comment by kxuenvoy** [comment]
Is there any guideline for  srb support for apollo fderation?

**Comment by daemonsy** [comment]
Hey @kxuenvoy I don't use sorbet myself, but there should be nothing that prevents this library from working with sorbet, like any other ruby library. From the error and the sorbet link, it looks like sorbet is saying the method `key` is present on `UserType`. 

Is the module included such that `Types::UserType.key` exists? i.e. like the example we have below in the README. 

```ruby
class BaseObject < GraphQL::Schema::Object
  include ApolloFederation::Object

  field_class BaseField
end
```

Otherwise, it would help if you can post more of your classes?

**Comment by daemonsy** [comment]
Based on what's posted so far, sorry I don't have a better idea of what's going on. If you think the problem is with the federation library, could you reproduce it in an open repo?
