### ISSUE TITLE
Development / maintenance status of this gem

### ISSUE THREAD

**Issue by jmpage** [Gusto/apollo-federation-ruby#267]
I'd like to start this issue by saying thank you for this gem and all of the hard work that the maintainers have put into developing it and triaging issues & PRs to it. I'm submitting this issue to help me understand what the plans are for the development and maintenance of this gem so that I can plan accordingly as a (grateful) user of it.

Per [the commit log](https://github.com/Gusto/apollo-federation-ruby/commits/main), it appears that no features or bug fixes have been added since June 2nd, 2023. Since then, commits to the gem have been exclusively dependency bumps, sans a minor documentation change.

I have noticed a few signs of triage but, for the most part, this gem seems dormant. In mid-September, it was mentioned on #263 that Gusto is reshuffling teams.

All this leads me to ask the following:

- Does Gusto still plan on developing or maintaining this gem?
- Are you looking for help on maintenance?
- If people want / need new features, would you prefer that they PR back to this gem or would you prefer them to maintain a separate fork to serve their needs?

Given that four months have passed without feature development and bug fixes and it has been a month since the comment on #263, I hope that the submission of this issue is timely and not premature. I appreciate any clarity that you are able and willing to provide!

**Comment by simoncoffin** [comment]
@jmpage thanks for raising this issue, and our apologies for the lack of communication here.

Unfortunately, I don't have concrete answers for you at this moment, but I can provide context. Also I will raise this issue to the team and get you a more definitive update as soon as I can. 

For context, the comment on [#263](https://github.com/Gusto/apollo-federation-ruby/pull/263) is accurate. We've been restructuring our infrastructure teams, and consequently are still in the process of outlining areas of ownership and how we handle long term commitments like this gem.

On the positive side, we now have a larger team primarily dedicated to working on our GraphQL related tooling and infrastructure. However, since several of us are new to company (e.g. myself) or to this specific team, there's a delay as we orient ourselves and prioritize. 

Again sorry I'm unable to give you more concrete answers at the moment, but I do want to emphasize that this internal alignment is among our top priorities, and we're working hard to get to a place where we're able to provide definitive guidance soon.

Feel free to ping me on this issue in a week or so if we haven't gotten back to you by then.

**Comment by jmpage** [comment]
@simoncoffin thank you for your prompt reply.

It's good to hear that this gem hasn't fallen by the wayside as of yet and that Gusto is growing its team related to GraphQL tooling and infrastructure.

No worries regarding not having concrete answers; I appreciate the one that you gave. I look forward to hearing more in the future.

P.S. Congratulations on the new role!

**Comment by simoncoffin** [comment]
Hey @jmpage,

Thanks again for asking about the gem's maintenance status. It's an important question, and the team has discussed it at length. 

For now, we've decided our maintenance of this gem is unlikely to extend beyond simple changes, such as bug patches, dependency bumps, and very minor tweaks. More significant changes, such as breaking changes, new features, or alterations to fundamental internal logic will be deprioritized. 

If you have an urgent need for a change to go through, we recommend you fork. We'll be more than happy to work with the community on merging their updates in the future. We anticipate being able to dedicate more resources to this gem in May 2024.

cc @sethc2 @sofie-c @slauppy

**Comment by jmpage** [comment]
@simoncoffin Thank you for the transparency and for following up!

**Comment by craig-day** [comment]
Hey @simoncoffin @sethc2 @sofie-c @slauppy, just wondering if there are any updates on this? The last date called out was May and there is lots of great pending work here. Do we have a better sense on getting the contribution pipeline flowing again?

**Comment by sofie-c** [comment]
Hey @craig-day, posted [here](https://github.com/Gusto/apollo-federation-ruby/discussions/280#discussion-7098391)!
